### ISSUE TITLE
Specify named parameter to WebDataset constructor

### ISSUE THREAD

**Issue by lvaleriu** [tmbdev/webdataset#1]
I think you have to make this transformation for all your WebDataset class initialisation.

ds = wds.WebDataset("testdata/imagenet-000000.tgz", 1000, decoder="pil")
=>
ds = wds.WebDataset("testdata/imagenet-000000.tgz", size=1000, decoder="pil")

**Comment by tmbdev** [comment]
The API has been overhauled, so this should not be an issue anymore.
