### ISSUE TITLE
Cannot specify ten/tb when using TarWriter

### ISSUE THREAD

**Issue by npuichigo** [tmbdev/webdataset#10]
I found that numpy array will be encoded to bytearray, which has conflict with the assertion of bytes.
```
sample = {
        "__key__": f"{i:05}",
        "tb": numpy_array,
        "cls": label
}
```
![image](https://user-images.githubusercontent.com/11533479/92434538-ab71a780-f1d2-11ea-8285-f18040fa6ba5.png)

![image](https://user-images.githubusercontent.com/11533479/92434358-356d4080-f1d2-11ea-8a9c-dfd195e079f7.png)

**Comment by tmbdev** [comment]
Thanks. I'll add a fix. TenBin exists primarily as a memory-mappable, GPU-friendly format that's used in conjunction with Tensorcom and C++ I/O pipelines.

For most applications, right now, I recommend using .pyd (Python pickles) or .pth (Torch pickles).

**Comment by tmbdev** [comment]
It should be working now.
