### ISSUE TITLE
Creating Webdataset from tar files

### ISSUE THREAD

**Issue by HamidShojanazeri** [tmbdev/webdataset#11]
I am looking for some help/advice to shard a video dataset into tar files and use it with webdataset. In a folder I have a number of  XX.mp4 (video), XX.info.json (script and action-labels) and XX.mp4.json (video metadata ). To use webdataset().decode() if I make a tar file out of each sample (i.e tar  000.tar -cf XX.mp4  XX.info.json  XX.mp4.json) then pass the files such as ds = wds.Dataset("/Users/../../data/tardb/{000..010}.tar").decode() then I can see the right keys in 

```
for sample in ds:
    for key, value in sample.items():
        print(key, repr(value)[:50])
    break

output	: dict_keys(['__key__', 'mp4.json', 'info.json', 'mp4'])
```

If I have multiple folders that in each folder there is a number of samples that share same base name as above XX.mp4, XX.info.json and XX.mp4.json, and then tar each folder and name it sequentially such as 

` tar -cf "db-{file_index}.tar" "db-{file_index}" `

Then ds = wds.Dataset("/Users/../../data/db-{0..10}.tar").decode(), the only key I see in the sample is only info.json 

```
dict_keys(['__key__', 'info.json'])
```
I was wondering what I am missing in this process/ what is a better way of making a webdataset out of such a data settings. Thanks.

**Comment by tmbdev** [comment]
When creating WebDataset data with `tar`, you need to use the `--sort=name` option:

    tar --sort=name -cf "db-{file_index}.tar" "db-{file_index}"

without it, files with the same basename may not end up adjacent to each other in the tar file. It is a good idea to verify file order in the tar file with "tar tf db-00000.tar" and make sure that files are grouped sequentially by file name.

You can also control the order of files added to the archive using a pipeline like:

    find . -name '*.json' -o -name '*.mp4' | sort | tar -cf archive.tar -T -

And even more general way of creating these archives is using the [tarp create](https://github.com/tmbdev/tarp) command, which lets you specify the exact order and composition of the resulting tar file using a two column text file, listing the archive file name in the first column and the file system file name in the second column.

NOTE: We should probably add a small command to check the validity of a WebDataset .tar archive.

**Comment by HamidShojanazeri** [comment]
@tmbdev Thank you, using the sort option the issue is resolved.

**Comment by tmbdev** [comment]
There is now a little command line program you can use for verifying that the .tar files are correct, as well as measure I/O speeds:

```
    $ python3 webdataset.bench shard-000000.tar
```
