### ISSUE TITLE
npy support

### ISSUE THREAD

**Issue by shayanfazeli** [tmbdev/webdataset#15]
in many cases reading tensor data using numpy.load is many times faster than loading a pickle file. Would it be possible to add it to the basic_handlers?

**Comment by tmbdev** [comment]
I'll add that as a feature.

**Comment by thecooltechguy** [comment]
Hi @shayanfazeli @tmbdev ,

Do you guys know how we can decode .npy files currently with webdataset?

Thanks

**Comment by shayanfazeli** [comment]
I think it is already added, please check [here](https://github.com/tmbdev/webdataset/blob/master/webdataset/autodecode.py#L76).
So my understanding (and I might be wrong) is that you can treat npy the same way that you treat json etc., and just let the webdataset handle it.

**Comment by loiccordone** [comment]
How about saving .npy files using TarWriter/ShardWriter? I currently use ".pyd" to do it but I wonder if using ".npy" would be lighter/faster.

**Comment by tmbdev** [comment]
.npy is supported now; it's one of the basic decoders (meaning, you get it simply with the .decode() filter).

**Comment by tcwalther** [comment]
@tmbdev I think it would be nice to add a default encoder for numpy as well. My workaround for other people looking for this:

```python
import webdataset as wds
import io
import numpy as np

def serialize_npy(array):
    stream = io.BytesIO()
    np.lib.format.write_array(stream, array, allow_pickle=False)
    return stream.getvalue()

handlers = wds.writer.make_handlers()
handlers['npy'] = serialize_npy

sink = wds.TarWriter("filename.tar", encoder=handlers)
...
```

**Comment by jacobbieker** [comment]
@tcwalther A PR #77 added an encoder for numpy arrays now too
