### ISSUE TITLE
Creating a Webdataset  .tar file

### ISSUE THREAD

**Issue by Adenov94** [tmbdev/webdataset#2]
I want use webdataset format to load data faster than usual. First of all, I have a folder with images and DataFrame with annotations for every image. 

I faced the issue, after creating the webdataset via TarWriter. The dataloader of Pytorch doesn't see any file and return empy file error. 

here is my code:

```def convert_into_wds(path):  
    #define Tarwriter 
    sink = wds.TarWriter('MyDataset.tar', encoder=True)
    #extracting all images name 
    basenames = [f for f in os.listdir(path) if f.endswith(".jpg")]
    #Take only up to 20000 images
    for basename in tqdm.tqdm(islice(basenames, 0, 20000)):
        with open (f'./images/{basename}', 'rb') as stream:
            image = stream.read()
        #annotations preprocessing
        annotation = np.array(annotations[annotations[1]==int(basename[:-4])].iloc[:, 1:11])
        annotation = annotation/np.sum(annotation)
        #json file
        dataset = {
            "__key__":basename[:-4],
            "jpg": image,
            "cls": annotation
        }
        sink.write(dataset)
    sink.close()
```
After creating, I tried to check it 
```!curl -s MyDataset.tar | tar tf - | sed 10q```
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

also another way:
```
url = f"pipe:curl -L -s MyDataset.tar || true"

dataset = (
    wds.Dataset(url)
    .shuffle(100)
    .decode("pil")
    .rename(image="jpg;png", data="json")
    .to_tuple("image", "data")
)

dataloader = torch.utils.data.DataLoader(dataset, num_workers=4, batch_size=16)
images, targets = next(iter(dataloader))
images.shape
```
Response:
File "/home/adil/anaconda3/envs/pytorch/lib/python3.7/tarfile.py", line 2304, in next
    raise ReadError("empty file")
   tarfile.ReadError: empty file

I am using 
Ubuntu 18.04
Visual Studio 

Environment Anaconda

Thanks in advance!

**Comment by tmbdev** [comment]
The code looks correct; did you find the source of the error? Please let me know so that I can improve diagnostic errors.
