### ISSUE TITLE
Multiple images in a sample?

### ISSUE THREAD

**Issue by ajtao** [tmbdev/webdataset#20]
I searched but couldn't find an answer to this ...

Suppose i have a dataset where there are multiple files with the same extension within a sample, such as a stereo dataset where there's a left and right image, but each share the same basename (by necessity with webdataset) and same file extension. Is this construct supported?

I was thinking to hack the file extension to add a key, such as: image0.png_left and image0.png_right, and then i'd just have to process these files, knowing what the special extensions mean.

**Comment by wooters** [comment]
I faced a similar situation. The approach I used was to add a second "extension". So, something like "foo0.left.png" and "foo0.right.png". I'm not sure if this is the recommended way to do it, but it worked well for me.
