### ISSUE TITLE
aws storage

### ISSUE THREAD

**Issue by shayanfazeli** [tmbdev/webdataset#21]
The google cloud storage buckets work well (for the most part) with this framework. Is there any suggested/preferred methodology to utilize the amazon s3 storage with this? (Putting tar files in that bucket and use the URL to load them in a local machine)

**Comment by tmbdev** [comment]
You can use any command line tool as a URL source. For S3, the following should work:

```Python
url = "pipe:s3cmd get s3://bucket/dataset-{000000..000999}.tar -"
dataset = wds.Dataset(url)...
```

(Note that this use of command line tools is actually more efficient than the Python-native S3 client; that's why WebDataset does not use Python-native cloud libraries by default for accessing any storage.)

**Comment by shayanfazeli** [comment]
Thank you @tmbdev . I tried this with a single tar file on AWS, the command line code works in terminal (meaning that s3cmd is configured properly), however, when running the above in python (using wds.Dataset and then starting to iterate) I get this:

`tarfile.ReadError: bad checksum`

More details:
`>>> for item, label in tqdm(dataset):
...     c+=1
...     if c>100:
...         break
...     continue
... 
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.6/tarfile.py", line 1037, in frombuf
    raise InvalidHeaderError("bad checksum")
tarfile.InvalidHeaderError: bad checksum`

Any idea why that is happening? If the same file is loaded from the local drive, it's ok.

**Comment by shayanfazeli** [comment]
Installing awscli using `pip install awscli` and then using this code:

```
'pipe:aws s3 cp s3://bucket/file.tar -'
```

seems to work. However, is it efficient? 
What are the best options for when we do/dont have sudo access?
Why doesn't the s3cmd get work?

**Comment by Nilabhra** [comment]
> Installing awscli using `pip install awscli` and then using this code:
> 
> ```
> 'pipe:aws s3 cp s3://bucket/file.tar -'
> ```
> 
> seems to work. However, is it efficient?
> What are the best options for when we do/dont have sudo access?
> Why doesn't the s3cmd get work?
> 
> often the "broken pipe" error occurs at some point throughout the training, more frequent with the aws, but happened with google storage as well.

I am also getting the broken pipe message when using `awscli` but only for specific files. It's strange since I can easily download those files using `awscli` directly.

**Comment by drscotthawley** [comment]
@Nilabhra Did you ever figure out the reason for the broken pipe? I'm getting the same thing for all files, despite being able to access the same files manually.

**Comment by Nilabhra** [comment]
@drscotthawley Unfortunately not. I had to build a retry mechanism so that I ended up downloading all the files. 

Your case seems serious though. Maybe our errors have different causes?

**Comment by oli-clive-griffin** [comment]
I'm getting a similar error, When using an ec2 instance and s3 for storage, I always get a broken pipe error (have tried with `num_workers=4` and `num_workers=0`) so haven't been able to get training started yet. Might be because my shards are too big? (≈1-3GB)

**Comment by rohit901** [comment]
Im using webvid-10m dataset, and the tar files are huge (2GB). I'm also getting the broken pipe error when using:
```
url = "s3://path/train/{00000..10727}.tar"
s3_url = f"pipe:aws s3 cp {url} -"
```
I believe it maybe because the command times out and is not able to download the entire tar file and pass it to the stdout? 

Is there any other way in which I can use webdataset with S3 URLs?

**Comment by rohit901** [comment]
Ok guys, i think I figured out the broken pipe issue maybe because of lack of CPU memory. I ran same code on AWS Instance (p4d) and didn't face the pipe issues.
