### ISSUE TITLE
Unable to reach maximum download speed

### ISSUE THREAD

**Issue by harpone** [tmbdev/webdataset#24]
I have an image dataset of about 250 1GiB tars on GCS, which I'm loading by using `urls = f'pipe:gsutil cat {urls}'`.

I tested the maximum download speed with `gsutil -m cp ...` and got about 750MiB/s with 96 processes (on a 96 vCPU GCP VM), which would amount to about 15000 images/s. I'm testing the data I/O only, no accelerators.

However, using `wds.MultiDataset` (96 workers) with basic decode, to_tuple etc steps (and minimal cropping with albumentations) and batching to 256 results in much slower download & processing, about 2500 images/s (this is actually already really fast but I'd like to try to get it even faster :D ).

So I'm not bottlenecked by download speed, and CPU utilization for the 96 processes shows <30%, so I'm not bottlenecked by the CPU either...

I profiled the code with pyinstrument and the bottleneck seems to be somewhere in the batching:
![Screenshot from 2020-10-09 15-11-46](https://user-images.githubusercontent.com/5112840/95581547-dce3ca00-0a41-11eb-945a-d6399f6d8426.png)

I'm working on non-public data, but basically same thing happens with the docs openimages example.

So given that gsutil -m results in fast download speeds but webdataset doesn't, and both use python (?) multiprocessing, maybe gsutil doing something more efficiently here? I don't really know the multiprocessing etc. libraries well at all so I'm at a bit of a loss here...

**Comment by tmbdev** [comment]
Although the profile shows `batched_` at the top of the stack trace, if you look further down, the actual overhead is in multiprocessing/queues.py; the reason this is attributed to `batched_` is because of the use of iterators. The batching itself takes place in `default_collation_fn`, which has fairly little overhead.

Is there any reason you are using `MultiDataset` rather than `DataLoader`? Have you tried `DataLoader`? `DataLoader` uses shared memory for large transfers, so it is more efficient in many cases. `MultiDataset` is useful in special cases, but it's still marked experimental.

Please let me know whether using `DataLoader` fixes the performance problem.

For really high performance, it's better to use `github.com/nvlabs/tensorcom`. That performs multithreaded I/O and will eventually support direct-to-GPU data transfers. It's a little different in that you separate the input pipeline from the training code; that actually helps debugging, scaling, and testing, but it's a somewhat bigger change than just dropping in `webdataset.Dataset`.

**Comment by harpone** [comment]
Oh I somehow thought `Multidataset` was the preferred approach! OK will try a `Dataloader` ASAP.

OK tensorcom sounds interesting too! I'll give the standard Dataloaders a spin first...

**Comment by harpone** [comment]
OK getting the max download speed of 12000 img/s with PyTorch `Dataloader`! :smile: 

Using a `.shuffle(10000)` slows it down to 9800 img/s, which is still blazing fast, but then batch "diversity" is about 10% (only 10% of frames are from different clips). I remembered that I was using MultiDataset because of the inter-batch shuffling mechanism, which really helped with the diversity issue... maybe that's also what's slowing down MultiDataset compared to Dataloader?

Using shuffle buffer of 100k => no further slowdown and diversity is about 40% eventually, but then I get `RuntimeError: DataLoader worker (pid 26180) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.`. That's a bit weird, because I'm seeing about 45G of shm used out of 180G... Increasing shm to 300G also doesn't help - crashes at about same iteration.

shuffle buffer = 1M doesn't seem to change anything...

Anyway, I'm tempted to drop the entire frame sampling thing, because I'm definitely _not_ going to give up using Webdataset! :smile:

**Comment by tmbdev** [comment]
Great news on the speed. I've tried to add a bit more explanatory text on MultiDataset. 

Some additional comments:

While MultiDatset makes .unbatch().shuffle(100000).batch(...) particularly concise, you can just compose the output of a DataLoader with the filter functions in webdataset.filters to get the same effect.  I'll try to make this a little simpler in upcoming versions of the code; filters.py will get IterableDataset as an API, and there may also be a MultiDataset-like wrapper for DataLoader.

For the shared memory, I'm not sure what limit you are setting. The default limit is 18 petabytes. Perhaps you're running out of shared memory segments?

**Comment by harpone** [comment]
hmm I meant just the OS shared memory, `/dev/shm`... my working machine has max. 360GB RAM, shared mem default seems to be half of that on GCP and I tested setting that to 300GB. Not sure about shm segments...

Anyway, the OOM doesn't seem to occur if I don't do the frame sampling, so probably something there. Also I think I'll be trying out another dataset so I won't have to worry about the sampling/shuffling thing for now.

**Comment by tmbdev** [comment]
You only get 4096 shared memory segments, and DataLoader may be using one per tensor. It's possible that you run out of segments rather than out of memory (the error message would likely be the same). Have you tried using ipcs to see actual limits and usage?

https://datacadamia.com/os/linux/shared_memory

I don't know what your code does in detail, but generally, it's much more efficient to transfer large batches to the DataLoader and then rebatch and reshuffle after the DataLoader (in fact, that's the way you get good performance out of MultiDataset as well).

(Incidentally, Tensorcom avoids all this by doing all the data transfers multithreaded in the background, and it can even use on disk I/O buffering if you want to pre-buffer very large amounts of data.)

**Comment by harpone** [comment]
Oh didn't know that, I'll take a look. Thanks for the tip! Yeah tensorcom is looking pretty interesting... maybe I'll give that a try too.

**Comment by harpone** [comment]
Oops forgot to close (max dl speed is reached).

**Comment by harpone** [comment]
hmm can't see anything with `ipcs -a` etc. Also tried setting `/proc/sys/kernel/shmmni` from 4096 to 8192 but that changed nothing...

Anyway, didn't realize batching should be done in the dataset as well! So I'm now trying that with PT DataLoader. I guess I need to use `batch_size=1` in dataloader kwargs, and of course the default collate function can't really handle already batched inputs so I'm just using an idendity collate function.

So I'm doing this (using the keys for the sampling part):
```
dataset = (wds.Dataset(urls)
           .decode('rgb8')  # dict with keys: __key__, jpeg, json
           .pipe(filter_nones)
           .to_tuple('__key__', 'jpg', 'json', handler=wds.warn_and_continue)
           .map_tuple(identity_fn, transform_fn, identity_fn)
           .batched(100)
           .pipe(generate_pairs)
           .shuffle(10000)  # apparently need both shuffles
           .pipe(batched(batchsize=256, partial=True, collation_fn=collate_webdataset))  # NOTE: DataLoader collate_ytbb_wds expects UNBATCHED inputs
           )
```

then

```
def collate_id(x_): return x_
dataloader = DataLoader(dataset, num_workers=96, batch_size=1, collate_fn=collate_id)
```
Speed is really good for 96 workers (won't necessarily need that many, but testing with that now), but I still get the shm OOM issue.

I think I'll give tensorcom a try next!

**Comment by harpone** [comment]
I'm trying out tensorcom, but having some compatibility issues... zcom.py is using `old_div` which apparently doesn't exist anymore on py3.7 or something. 

Also, the data loading logic seems exactly same as what I was doing above, except for the `serve.send([x, y])`, so probably the OOM issue will persist here too.

FYI the OOM issue was _not_ due to the frame sampling. I'm getting it all the time now. Takes a lot longer to occur with fewer dataloader workers, but it's still there.

`ipcs` doesn't show anything for me about which PID is using which shm etc. I had some luck with `lsof /dev/shm`, which shows something like following:

```
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF  NODE NAME
python3 12515 heka  DEL    REG   0,22           816675 /dev/shm/pym-8888-edivz7ql
python3 12515 heka    3u   REG   0,22      4096 816675 /dev/shm/pym-8888-edivz7ql (deleted)
python3 12515 heka    4u   REG   0,22      4096 816675 /dev/shm/pym-8888-edivz7ql (deleted)
python3 12527 heka  DEL    REG   0,22           854274 /dev/shm/pym-8893-7iyu0rvh
python3 12527 heka    3u   REG   0,22      4096 854274 /dev/shm/pym-8893-7iyu0rvh (deleted)
python3 12527 heka    4u   REG   0,22      4096 854274 /dev/shm/pym-8893-7iyu0rvh (deleted)
python3 12574 heka  DEL    REG   0,22           841651 /dev/shm/pym-8937-vrtoo0m6
python3 12574 heka    3u   REG   0,22      4096 841651 /dev/shm/pym-8937-vrtoo0m6 (deleted)
python3 12574 heka    4u   REG   0,22      4096 841651 /dev/shm/pym-8937-vrtoo0m6 (deleted)
python3 12640 heka  DEL    REG   0,22           841651 /dev/shm/pym-8937-vrtoo0m6
python3 12640 heka    3u   REG   0,22      4096 841651 /dev/shm/pym-8937-vrtoo0m6 (deleted)
python3 12640 heka    4u   REG   0,22      4096 841651 /dev/shm/pym-8937-vrtoo0m6 (deleted)
```

the number of these entries seems to saturate to about 16k when using 96 workers (results in OOM after 1450 iterations), and to about 4800 for 48 workers (results in OOM after 3450 iterations). Not sure what this has to do with the shm segments...

**Comment by harpone** [comment]
aargh I was actually out of RAM, not shared memory! Somehow only up to 10% of shm is utilized... looking into it.
