### ISSUE TITLE
Help in creating tar archive for webdataset using tarfile python package

### ISSUE THREAD

**Issue by mukulkhanna** [tmbdev/webdataset#26]
Hello,

Could someone help me with what the equivalent to (from your [docs](https://webdataset.readthedocs.io/en/latest/#creating-a-webdataset)) -
```
$ tar --sort=name -cf dataset.tar dataset/
```
would be using the [tarfile](https://docs.python.org/3/library/tarfile.html) Python package. The above command is able to collate the files with a common basename into one group with a common key. It seems to me that this is taken care of by the `--sort=name` param.

I am trying to create a similar tar archive using the tarfile python package. This is the code that I'm using so far - 
```
     with tarfile.open(archive_path, "w") as tar:
         tar.add(dataset_path, arcname=os.path.basename(dataset_path))
```

But this doesn't group the files with a common basename into one key, as is required by webdataset to process a sample.

(I've already tried Webdataset's `TarWriter`, but with a large dataset like the one I'm using, my system runs out of memory when I create a tar archive using `TarWriter`)

Any help is appreciated, thanks!

**Comment by tmbdev** [comment]
First, we don't know of any memory leaks in the `TarWriter` class, and it has been used to create tar files that are terabytes large. It would be helpful if you could track down the source of the memory leak in your application; my guess it is somewhere other than `TarWriter`, but if there is a memory leak in it, we would like to fix it. You may find a Python memory profiler helpful, something like `objgraph`, `PySizer`, or `Heapy`.

Another option you have is to use the `tarp create` command [here](https://github.com/tmbdev/tarp). On its standard input, it takes a list of files and it produces a tar archive as an output; unlike the `tar -F -` command, you can specify both a source file name and the name in the archive. For example, to create an image classification WebDataset, you create a text file containing lines of the form:

```
image00001.txt text:9824"
image00001.png file:./data/c9824/img1.png
image00002.txt text:121
image00002.png file:./data/c121/img17.png
...
```

Note that you can specify both inline data (`text:` prefix) and data coming from a file or program (`file:` or `pipe:`) prefix.

**Comment by mukulkhanna** [comment]
Thanks for the help. I'll re-examine the memory issue.

I figured out the `tarfile` code - I was initially trying to archive the directory directly. 
Adding to the archive file by file worked as I wanted it to.

```
with tarfile.open(archive_path, "w:gz") as tar:
        for file in sorted(os.listdir(dataset_path)):
            tar.add(os.path.join(dataset_path, file))
```
