### ISSUE TITLE
What is the meaning of `maxsize` argument for `ShardWriter`?

### ISSUE THREAD

**Issue by pkubik** [tmbdev/webdataset#27]
I have hard time figuring out what `ShardWriter(..., maxsize=32e6)` actually means. I assume it's the size of each shard, but it's not consistent with my observations. I guess it's measured in bytes, in which case 32e6 = 32MB.

I stored small png images and each shard was consistently larger than 32MB (from 60 to 80MB). I moved to `tar.gz` with `compress=True` and the size started to closely match 32MB which is already odd.
Later I had to move to raw `pth` files for my examples, and each shard was around 9MB... Tried uncompressed version and it jumped to 39MB.

I guess the png case could be caused by internal fragmentation, because each file was ~1KB (< 4KB), but I'm not sure if that's an issue in a tar archive. Compression would be highly ineffective for png so I guess it would at most remove the internal fragmentation which led to accurate size.
In case of the `pth` I'm puzzled. Compression rate is much higher, since raw image arrays have a lot of redundancy so it makes sense that 32MB archive could be compressed down to 9MB. On the other hand, I have no idea why the uncompressed version is slightly bigger?

**Comment by pkubik** [comment]
Oh, my bad. I didn't consider that internal fragmentation might still occur even though each `pth` file is larger than 4KB. I checked that each `pth` is around 7.7KB which could explain why 32MB data shard ended up taking slightly more space. Yet, 8KB - 7.7KB = 0.3KB ~= 5%, so it doesn't likely explain 39MB - 32MB = 7MB ~= 20% gap in the shard size.

**Comment by tmbdev** [comment]
`ShardWriter` estimates shard size based on the total number of content bytes, not the actual file size of the shard on disk; the overhead from the tar format and container is not accounted for. If you write small files, this overhead might become significant. We'll try to make the estimates more accurate in the future.

**Comment by pkubik** [comment]
Ok, fair enought.
