### ISSUE TITLE
[Question] DALI and object detection

### ISSUE THREAD

**Issue by austinmw** [tmbdev/webdataset#28]
Hi, does webdataset support NVIDIA DALI? If so, are there any examples? If not, do you happen to have an idea of how the data loading speed would compare (say for example using V100's and dali.ops.COCOReader)?

-------
**Context for my question if you have the time:**

I'm looking for the fastest way to load data in PyTorch for a very large (2TB) object detection dataset.
I'm using AWS, and my required region is limited to S3, EBS, or EFS for data storage.

My first consideration was DALI + sharded COCO files [as in this example](https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/dali.py#L8), however, since my dataset is very large, I suffer from large transfer overhead when starting training jobs (I use SageMaker, so the entire training set is transfered from S3 to a mounted EBS volume when training is kicked off [or alternatively, a slower and more expensive persistent EFS volume can be mounted]).

I would like to set up a named pipe to stream data from S3 to my training instances (distributed horovod), but am unsure how fast the data loading would compare to the DALI+COCO option. Any advice would be greatly appreciated.

**Comment by tmbdev** [comment]
You can use DALI with WebDataset; basically, you use WebDataset to read the compressed image/video data into memory and then set that data as input to your DALI pipeline using Python code. (Down the line, we're planning on adding WebDataset I/O directly to DALI.) DALI is fast at decoding images, but it consumes substantial amounts of GPU memory.

Alternatively, you can also use github.com/tmbdev/tensorcom in separate processes to do all the decoding using CPUs and then transfer decompressed tensors to the GPU directly. This gives rise to a three-tier architecture (storage to CPU decoder via WDS, CPU decoder to GPU via Tensorcom). While CPU cores are individually much slower at decompressing image data, they are very cheap, and you can scale them up arbitrarily. In particular in the cloud, that's likely the better solution.
