### ISSUE TITLE
TarWriter Error when given full pathname

### ISSUE THREAD

**Issue by Mikioma88** [tmbdev/webdataset#29]
Hello,

I am running into an error when providing the entire pathname of the destination tar file to the TarWriter function:

```
sink = wds.TarWriter('D:/dataset/dataset.tar', encoder=False)

ValueError: objectio: D:/dataset/dataset.tar: no handler found for d (known: file gs http https az)
```

However, this works:

`sink = wds.TarWriter('dataset.tar', encoder=False)`

How can I specify where I want my tar file written?

Thanks in advance!

**Comment by tmbdev** [comment]
I believe this should work (however, I don't have a Windows installation right now to test it):

```
sink = wds.TarWriter('file:D:/dataset/dataset.tar', encoder=False)
```

WebDataset really uses URL syntax and parsing, and the old DOS paths are not compatible with that. For that reason, Windows itself provides alternative ways of referencing files, so you _might_ also be able to use one of those alternatives, e.g.:

```
sink = wds.TarWriter('//./D:/dataset/dataset.tar', encoder=False)
```
