### ISSUE TITLE
allow starting shard numbering above 0

### ISSUE THREAD

**Issue by davzaman** [tmbdev/webdataset#30]
I am saving a persistent stream of data over long periods of time and saving them. Occasionally the script dies and I need to restart it. However, then it will overwrite the original files. It would be nice to be able to start from some number > 0 in these cases. The fix is relatively easy.

On [this line](https://github.com/tmbdev/webdataset/blob/759da058c65f16964391cdb575e2e66b078313a9/webdataset/writer.py#L294) in the ShardWriter class (the constructor for ShardWriter class) just add an optional parameter `shard_num` with default value 0 (i.e. `shard_num=0,` and then in the constructor (line 302) just set the shard to this number: `self.shard = shard_num`.

**Comment by tmbdev** [comment]
Will add this in the next release.

**Comment by tmbdev** [comment]
Should be working now (start_shard argument).
