### ISSUE TITLE
Serious drop in data loading speed observed

### ISSUE THREAD

**Issue by harpone** [tmbdev/webdataset#31]
Has anyone else noticed download issues with webdataset, about 10x drop in data loading speed? I'm observing slowdowns with everything (on GCS at least), for example also the @tmbdev 's openimages dataset...

Please see the gist [here](https://gist.github.com/harpone/71faadbbcb9bbe20923de9306d4cf091). Should be ready to run.

In my earlier benchmarks I was able to get about 2000 img/s with 8 processes with the above script (50 minibatches of size 256 in about 6.5 s), but now I'm getting about 400 img/s top.

I'm on a GCP VM. Tried downgrading various libraries, spun up a VM from an image from last July etc... gsutil multiprocessing downloads from GCS are still very fast (~570MiB/s => 11400 openimages img/s) 

I'm totally confused what's going on!

**Comment by harpone** [comment]
Actually I'm getting same slowdown when loading from disk... anyway, here's a profiler output with the above gist using batch_size=256 and num_workers=8:
![Screenshot from 2020-12-03 13-28-37](https://user-images.githubusercontent.com/5112840/101012581-b8046280-356b-11eb-91b6-7e2de9543813.png)

Lots of time spent on waiting in multiprocessing poll.poll...

**Comment by harpone** [comment]
@tmbdev can you tell me what kind of data load speeds you've gotten with your openimages dataset? Earlier (e.g. in this issue https://github.com/tmbdev/webdataset/issues/24) I was getting up to 12k img/s but now I'm getting max 10% of that, irrespective of the number of workers (and with pytorch dataloader, tried with pt versions 1.7 and 1.6)...

I'm starting to suspect my earlier benchmarks (or my sanity), although I *did* do several of them and with essentially the same script as in the gist.

**Comment by tmbdev** [comment]
(I'll be looking into this in a couple of days.)

**Comment by harpone** [comment]
Actually I probably made a mistake with my earlier benchmarks: I was probably using a lower resolution version of openimages than your original size (?) version. Also the multiprocessing seems to have hidden the real time cost, which seems to be the jpeg decoding... at least that's what I'm looking into right now.

Anyway, given the data IO is now no longer the bottleneck, but JPEG decoding is (at least for large images), I'm also looking into storing the images as something else, e.g. compressing the uint8 image arrays with blosc, which results in higher storage but faster decompression. @tmbdev do you have some other suggestions for this?

Still, would be nice to have some "official" numbers on the data loading speed!

But I'm closing since this is not a real issue with the code.

**Comment by harpone** [comment]
Just want to clarify a bit more that the problem indeed wasn't with webdataset - it's working absolutely beautifully and I observe practically no difference whatsoever when comparing to randomly generated data. Doesn't even need more than 1-2 dataloader workers per accelerator!

FYI I fixed the issues by using libjpeg-turbo for JPEG decoding, and blosc compression for segmentation maps (earlier I was using PNGs, which was really fast for relatively lo res segmentation maps with few classes, but turns out that's really slow for more classes and higher resolution).
