### ISSUE TITLE
How exactly does shuffling work in webdataset?

### ISSUE THREAD

**Issue by tueboesen** [tmbdev/webdataset#33]
I found this project today and it looks very promising for my work. However, I can't really find information about how shuffling is handled with webdataset. 

I see that I can do shuffling as follows:
```
dataset = (
    wds.Dataset(url)
    .shuffle(100))
```
However I'm uncertain what exactly the 100 means in this case? and similarly the 1000 that I see in another place in your examples. When I check in the code I find this definition of shuffle, which unfortunately doesn't make me any wiser to the details:
```
    def shuffle(self, size, rng=None, **kw):
        """Shuffle the data."""
        if size == 0:
            return self
        if rng is None:
            rng = random.Random()
        self.rng = rng
        self.reseed_hook = self.reseed_rng
        self.shard_shuffle = Shuffler(rng)
        self.pipeline.append(filters.shuffle(size, rng=rng, **kw))
        return self
```

In my general use case I have about 2.1 billion datapoints, which I want to save and start training over. I want to ensure that the shuffling done in webdataset actually enables a complete sampling of all datapoints before any datapoints are repeated in training.

**Comment by tmbdev** [comment]
WebDataset shuffles at three levels. First, datasets are generally shuffled before even being written in WebDataset format (but that's just a fixed shuffle). Then, WebDataset divides datasets into shards and reorders the shards randomly before reading. Lastly, it maintains an in-memory shuffle buffer; roughly, as samples are read they are added to the buffer, and random samples from the buffer are returned as the actual stream of samples.

The combination of shard shuffling and inline buffer shuffling always returns all data points exactly once during each epoch; that is, it is a permutation of the entire dataset.

You can make various tradeoffs between shuffling, performance, memory usage, and dataset size. Generally, when you divide your dataset into shards that are comparable in size to the shuffle buffer, you get something that's statistically similar to a fully random shuffle of the dataset. Often, that's easy to do (just pick shard sizes of 1-10 Gbytes and pick a correspondingly sized shuffle buffer or larger).

If you pick a shuffle buffer that's much smaller than a shard, you don't get full randomization, but it's usually still fine for deep learning. It's a good idea, though, to pick a shuffle buffer size that's at least as large as several batch sizes.
