### ISSUE TITLE
> Installing awscli using `pip install awscli` and then using this code:

### ISSUE THREAD

**Issue by Nilabhra** [tmbdev/webdataset#35]
> Installing awscli using `pip install awscli` and then using this code:
> 
> ```
> 'pipe:aws s3 cp s3://bucket/file.tar -'
> ```
> 
> seems to work. However, is it efficient?
> What are the best options for when we do/dont have sudo access?
> Why doesn't the s3cmd get work?
> 
> often the "broken pipe" error occurs at some point throughout the training, more frequent with the aws, but happened with google storage as well.

I am also getting the broken pipe message when using `awscli` but only for specific files. It's strange since I can easily download those files using `awscli` manually.

_Originally posted by @Nilabhra in https://github.com/tmbdev/webdataset/issues/21#issuecomment-758579696_

**Comment by tmbdev** [comment]
Yes, pipes like that are efficient: in Python, you need separate I/O processes anyway, and running the native command line tool for accessing file servers is usually the most efficient.

I'm not sure why s3cmd doesn't work for you; generally, any command line program works.

Note that if you have complex I/O or error handling needs, it's perfectly fine to write a shell script:

    pipe:my-shell-script sed://bucket/file.tar

Shell scripts might ignore particular exit codes, ignore all errors, set up a particular environment, etc. For example:

                #!/bin/bash
                source $HOME/venv/bin/activate
                python -m some.client.library "$@" || true
