### ISSUE TITLE
How to undersample a class with WebDataset?

### ISSUE THREAD

**Issue by loiccordone** [tmbdev/webdataset#37]
Hello,

I'm using WebDataset to store and load ~400 tar files containing 40k samples, with 89% of the data being class 0 and the other 11% class 1. I want to undersample the class 0 to obtain a balanced dataset, and I can't seem to do it. I've tried to use WeightedRandomSampler but it doesn't work with IterableDataset, so what is the best approach to do this with a WebDataset?
I'd like to avoid recreating tar files with only 10% of my class 0 because ideally I'd like to sample 10% of my class 0 randomly when the Dataloader is created.

I'm open to all ideas, thanks in advance!

**Comment by tmbdev** [comment]
There are several different approaches you can take:

- Read the data sequentially as before, but drop samples of the more frequent class. This is often more efficient even than random access datasets. It's a good idea to first decode the class label, then decide whether to drop the sample, and only decompress images for those samples you don't drop.
- Split your shards by class, e.g., `data-{0..9}-{0000..0099}.tar`. You can instantiate separate WebDataset readers for each class and sample round-robin, then shuffle.
- Generate a larger dataset that replicates infrequent classes to equalize frequencies. Shard and sample shuffling will still randomize sample order sufficiently afterwards. This will increase the size of your epoch substantially.

All of these preserve the advantages of sequential I/O.

Generally, I prefer the last approach, that is, generating a new dataset. It's the most easily reproducible and testable.
