### ISSUE TITLE
Issue next release?

### ISSUE THREAD

**Issue by jhlusko** [tmbdev/webdataset#38]
Is the current version suitable for release?

I'm trying to package a webdataset dependent app for google's ai-platform, and it can install from pip, but not from git.

Thanks!

**Comment by penguinmenac3** [comment]
I agree, a more up to date version on pypi would be great!

**Comment by tmbdev** [comment]
Sorry, I was traveling. Normally, the pip packages are built automatically, but for some reason the tests are failing on Github. I'll try to fix it.

**Comment by tmbdev** [comment]
OK, there were a bunch of cleanups that needed to be done after the merge of the dev branch. Everything should be working now.
