### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by raman-rajarathinam** [tmbdev/webdataset#41]
**Install**

```sh
pip install webdataset==0.1.49
```

---

**Code**
```py
import webdataset
...
```

when I run this program, it throws 
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raman/miniconda2/envs/temp/lib/python3.8/site-packages/webdataset/__init__.py", line 28, in <module>
    from .writer import ShardWriter, TarWriter, torch_dumps
  File "/home/raman/miniconda2/envs/temp/lib/python3.8/site-packages/webdataset/writer.py", line 17, in <module>
    import PIL
ModuleNotFoundError: No module named 'PIL'
```
---

Should we install PIL separately? or this is a bug?

**Comment by mynameisvinn** [comment]
ah that's because Pillow was not included in [requirements.txt](https://github.com/tmbdev/webdataset/blob/master/requirements.txt).

For now, do `pip install Pillow` and then it should work. I will submit a PR to fix this problem.

**Comment by tmbdev** [comment]
Thanks; I'll have a look. Installing Pillow by hand is a quick workaround.

**Comment by tmbdev** [comment]
I've added Pillow to the default requirements. However, you can use the library without PIL/Pillow if you like (PIL is now only loaded when you are trying to decode images).
