### ISSUE TITLE
TypeError: rename_() got multiple values for argument 'data' #3

### ISSUE THREAD

**Issue by sampathkumaran90** [tmbdev/webdataset#43]
Facing this issue while using 

`dataset = (
        wds.Dataset(url)
        .shuffle(1000)
        .decode("pil")
        .rename(image="jpg;png", i="json")
        .map_dict(image=preproc)
        .to_tuple("image", "i")
    )`

**Comment by tmbdev** [comment]
wds.Dataset is the old API.

Just switch to wds.WebDataset and your code should work.
