### ISSUE TITLE
torchvision warning

### ISSUE THREAD

**Issue by pratogab** [tmbdev/webdataset#44]
I get the following warning when using the `torch_video` decoder:
_torchvision/io/video.py:116: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'._

The solution would be to change line 221 in webdataset/autodecode.py:
```python
return torchvision.io.read_video(fname)
```
to:
```python
return torchvision.io.read_video(fname, pts_unit='sec')
```

**Comment by tmbdev** [comment]
fixed
