### ISSUE TITLE
Not compatible with python 3.8+?

### ISSUE THREAD

**Issue by bjuncek** [tmbdev/webdataset#45]
when trying to install the library I'm getting the following error. Is that supposed to happen and python 3.6 is a hard requirement or is it a bug? 

```
Requirement already satisfied: dataclasses in /envs/pfe_submit/lib/python3.8/site-packages/dataclasses-0.8-py3.8.egg (from torch->webdataset==0.1.49) (0.8)
ERROR: Package 'dataclasses' requires a different Python: 3.8.5 not in '>=3.6, <3.7'
```

Best,
Bruno

**Comment by tmbdev** [comment]
I'm not sure where that error comes from, but webdataset doesn't use "dataclasses" and works fine with Python 3.8.

Are you trying a system-wide installation? You may have a version conflict there.

Try installing with virtualenv:
                
                $ cd webdataset
                $ pip3 install invoke  # this is in your system Python
                $ invoke venv
                ...
                $ . venv/bin/activate
                $ python
                >>> import webdataset

If you still think it's related to webdataset, please reopen the bug and provide more information.
