### ISSUE TITLE
Usage with s3 image buckets

### ISSUE THREAD

**Issue by mathieuorhan** [tmbdev/webdataset#46]
Hi, 

I'm trying to find a solution to stream images from s3 buckets in PyTorch, something like: bucket/{image_ids}.jpg for tons of images.
Suppose I cannot change way data are stored, is it possible to use this project to stream from s3 buckets?

Thank you!

**Comment by tmbdev** [comment]
You can use any command line program you like as a data source; so, for S3, you can use a URL like:

    url = "pipe:s3cmd get s3://mybucket/dataset-{000000..000999}.tar -"
    ds = WebDataset(url).decode("rgb")

This will use 1000 shards in the s3://mybucket bucket as input.

(Note that all I/O is handled using "pipe:" internally, since it's a very efficient way of doing it in Python.)
