### ISSUE TITLE
Open to a PR for compressed tar input?

### ISSUE THREAD

**Issue by singularperturbation** [tmbdev/webdataset#5]
This is a really nice library!  I just came across it after going down a rabbit hole looking into distributed training with TorchElastic and planning how data loading would work.  (Most tutorials I see now are either bundling the data into the docker image, creating a K8s volume and then running a job to pre-fetch the data before training, or creating an NFS volume).

I was wondering if you'd be open to a PR for adding compressed tar files as input (.tar.gz, etc.)  I think that this would be pretty easy to add but wanted to see if there were any objections before looking into it.

**Comment by tmbdev** [comment]
Compressed tarfiles should simply open (tarfile.open uses mode "r|*"), so no patch is needed. If you're having problems with that, please submit a bug report.

Generally, you're better off storing compressed files and leaving the .tar file uncompressed; the storage overhead is small for most datasets and it consumes much less CPU. In addition, uncompressed .tar files can be indexed and support random access with FUSE and other libraries.
