### ISSUE TITLE
Include cache related args in Dataset class

### ISSUE THREAD

**Issue by nateraw** [tmbdev/webdataset#50]
### Feature Request

The `wds.WebDataset` class lets you define `cache_dir`, `cache_size`, `cache_name`, and `cache_verbose` args. It would be helpful to be able to provide these when instantiating classes directly with `wds.Dataset`. Something like this:

```python
from webdataset import Dataset

ds = Dataset(urls, cache_dir='my_cache/')
```

### Motivation

I have been subclassing `wds.Dataset` and would like my subclasses to have ability to cache. I chose this as the parent class for my use case as I noticed its just wrapping calls to `wds.WebDataset`.

### Potential Solution

I'll submit a simple PR that does this w/o any breaking changes, but if I am instead mistaken and missing functionality from elsewhere, let me know! :smile:

**Comment by tmbdev** [comment]
The Dataset class is obsolete and only exists for backwards compatibility. The WebDataset class is a direct drop-in replacement.

Is there any reason you want to still use Dataset?

**Comment by nateraw** [comment]
I was using Dataset since it is an actual class instead of a function. That way I can make child classes with task-specific serialization/deserialization methods. 

I could get around this other ways if Dataset becomes officially deprecated, but it just happened to be the first approach I thought of. :smile:
