### ISSUE TITLE
Decoupling Pipelines from Training Nodes

### ISSUE THREAD

**Issue by ljstrnadiii** [tmbdev/webdataset#52]
Hello and thanks for the awesome project! I have been using it a ton and am successfully using it with with azure blob and azcopy. 

I wanted to ask a question about potentially decoupling the data pipeline from the training node (where gpu(s) live(s)).

With single GPU or Multiple GPU nodes, often I can not get enough CPU power to keep up with the GPU. I have thought about decoupling the data pipelines from the gpu. What I am imaging is anything from a designated large cpu instance or kubernetes cluster that sends the batch results from webdataset to the training node. This is outside the scope of webdataset, but I figured you might have some insight into this realm.

In my mind, the cpu, data pipeline instance/cluster should focus on pulling down data from cloud storage, apply transforms and prep data for dataloader.

Some ideas so far: 
- create transformed tars with torch tensors, drop into minio (or something similar) from remote servers, read tar from minio on training nodes.
- something like https://www.tensorflow.org/api_docs/python/tf/data/experimental/service.

Any thoughts? With this approach, the only limitation on arbitrary batch per second rates is network bandwidth and number of cpus on server/cluster.

**Comment by tmbdev** [comment]
Thanks! 

The companion project at github.com/nvlabs/tensorcom provides distributed preprocessing for just this reason.

In addition to providing distributed data augmentation, it also has a broadcast mode for training multiple clients from a single data server, for example for hyperparameter optimization.
