### ISSUE TITLE
Is there a reason the decode function excludes tif images?

### ISSUE THREAD

**Issue by cwerner** [tmbdev/webdataset#56]
Hi.

I'm trying to use webdataset to access my training samples more efficiently (avoid the 100000 files problem on my disk).
After a while I realised that the decode("pil") method cannot decode tif images (my source is a massive orthodox photo geotiff >320GB that I tile into 512x512px tifs)? I tried to follow the docs' decode notebook to build a custom tif decoder but have not had any success there... As a test, I used PIL.Image directly to read my tifs and it converts them happily.
Is there a reason this is not allowed in the Webdataset codebase (the auto decode function does not list tif as a supported format)...?

Are there any more examples of custom decode implementations?

Cheers,
C

**Comment by tmbdev** [comment]
The ".tif" extension is simply not in the list of recognized extensions. TIFF file decoding tends to be pretty slow, so it's generally not recommended in high performance code, however.

The .decode() method is just a convenience method, a kind of special form of .map(). If you want a decoder for TIFF files, you should be able to write:

```
def tiff_decode(key, data):
    if not key.endswith(".tif"):
        return None
    result = ... decode data ...
    return result

...
dataset = dataset.decode(tiff_decode, pil)
...
```

You can always just decode whatever you like with a .map(), which receives the whole sample:

```
def completely_custom_decoder(sample):
    sample = dict(sample)
    sample["tif"] = tiff_decoder(sample["tif"])
    return sample

...
dataset = dataset.map(completely_custom_decoder)
...
...

I'm also making the list of extensions for ImageDecoder configurable, so that you can add other extensions to be handed to PIL. It's in the Github version now. You should be able to say:

```
dataset = dataset.decode(ImageDecoder(extensions="png tif jpg".split())
```

**Comment by cwerner** [comment]
Thanks for the clarification and quick improvement!

**Comment by cwerner** [comment]
Quick followup if you don't mind:

Whenever I try to define a custom decode method I get the error:

```
  File "/opt/conda/lib/python3.8/site-packages/webdataset/iterators.py", line 228, in map
    result = f(sample)
  File "/opt/conda/lib/python3.8/site-packages/webdataset/autodecode.py", line 332, in __call__
    return self.decode(sample)
  File "/opt/conda/lib/python3.8/site-packages/webdataset/autodecode.py", line 327, in decode
    result[k] = self.decode1(k, v)
  File "/opt/conda/lib/python3.8/site-packages/webdataset/autodecode.py", line 307, in decode1
    result = f(key, data)
  File "/opt/conda/lib/python3.8/site-packages/webdataset/autodecode.py", line 133, in g
    return f(data)
TypeError: __call__() missing 1 required positional argument: 'data'
```

I now have a "rgb.png" and "msk.png" key in my sample (also txt but this should be ignored)...?

I call it like this:

```
[...]

wds.WebDataset(train, length=int(1e9))
    .decode(
        wds.handle_extension("rgb.png", wds.imagehandler("torchrgb")),
        wds.handle_extension("msk.png", wds.imagehandler("torchl")),
    )
    .rename(image="rgb.png", mask="msk.png")
    .to_tuple("image", "mask")
```

**Comment by cwerner** [comment]
Ok. I think I'm getting the hang of it now! Please disregard the last comments... 

Ans thanks again for providing this package to the public! Hopefully this work gains some traction and community support 👍
