### ISSUE TITLE
How to use webdataset for customized dataset class?

### ISSUE THREAD

**Issue by XuyangBai** [tmbdev/webdataset#60]
Hi Thanks for sharing this excellent work. I wonder is there any tutorials about using webdataset for the customized datasets. Specifically, my model is about point cloud, thus the loading and data augmentation process are quite different from images, and I have implemented the dataset class in PyTorch. So Is there any easy way to wrap my dataset by webdataset? The documents here are mostly about imagenet which can be directly loaded and processed by tools from PyTorch so I have no idea where to start.

**Comment by tmbdev** [comment]
If your point cloud training data is stored in JSON, Python pickle, or NPY dump files, you don't need to do anything. Let's say your dataset is stored on disk as:

```
001234.input.npy
001234.output.npy
009133.input.npy
009133.output.npy
```

and you want to augment each sample with a function:

```
def my_augmentation(sample):
    inp, out = sample
    ...
    return augmented_inp, augmented_out
```

then 

```
dataset = WebDataset("file.tar").decode().to_tuple("input.npy", "output.npy").map(my_augmentation)
```

will be enough.

If you need to do additional decoding, just write a function. Let's say your data is stored in ".pcd" (pointcloud) files. Then you can write:

```
def pcd_decoder(key, data):
    if not key.endswith(".pcd"):
        return None
    result = ... decode data ...
    return result
```

and

```
dataset = WebDataset("file.tar").decode(pcd_decoder).to_tuple("input.pcd", "output.pcd").map(my_augmentation)
```

**Comment by XuyangBai** [comment]
Thank you so much !

**Comment by haofanwang** [comment]
Helpful!
