### ISSUE TITLE
Using a second Webdataset inside a pipe transformation results in a non-halting program

### ISSUE THREAD

**Issue by nikvaessen** [tmbdev/webdataset#61]
### Problem

I am interested in using a dataset of background noise to use for on-the-fly augmentation of an automatic speech recognition dataset. I run in to the issue that the dataloader of the background data  uses the same `num_workers` as the dataloader from the main training data, even though it's explicitly set to 0. This then results in the program never exiting (it never manages to complete a single loop over the training data). 

### Code to reproduce the bug

```python3
import webdataset as wds
import torch as t

from torch.utils.data import DataLoader

# create the toy dataset (consisting of 10 shards)

with wds.ShardWriter("shard-%03d.tar", maxcount=10) as w:
    for i in range(0, 100):
        w.write(
            {"__key__": str(i), "x.pyd": t.Tensor([i]), "y.pyd": t.Tensor([i ** 2])}
        )

# create some noisy data to 'augment' the toy data during training (consisting of 5 shards)

with wds.ShardWriter("noise-%03d.tar", maxcount=10) as w:
    for i in range(0, 50):
        w.write({"__key__": str(i), "noise.pyd": t.rand((1,))})


# set up the augmentation functionality

noise_data = wds.WebDataset("noise-{000..004}.tar").decode("pil").repeat().shuffle(10)


class Augmenter:
    def __init__(self, noise_source: wds.Processor, num_workers=0):
        self.iter = iter(DataLoader(noise_source, num_workers=num_workers))

    def get_noise(self):
        noise_dict = next(self.iter)

        return noise_dict["noise.pyd"]

    def augment(self, sample: dict):
        augmented_x = sample["x.pyd"] + self.get_noise()

        return {**sample, "x.pyd": augmented_x}


# create main data pipeline to 'train' on


def pipe_fn(ds_to_transform):
    augmenter = Augmenter(noise_data, num_workers=0)

    for x in ds_to_transform:
        yield x
        yield augmenter.augment(x)


ds = wds.WebDataset("shard-{000..009}.tar").decode("pil").pipe(pipe_fn)

# non-halting loop when num_workers >= 6
loader = DataLoader(ds, num_workers=6, batch_size=None)

for s in loader:
    print(s)


```
### Potential solutions

* Create the dataloader with 0 workers first
* explicitly split the augmented data in more than or an equal amount of shards as the amount of workers you're planning to use
* modify https://github.com/tmbdev/webdataset/blob/fd375a61155d15e0360652a5b6cdc82dc6e6fcf5/webdataset/workerenv.py#L104 to respect individual arguments of a dataloader?

**Comment by tmbdev** [comment]
You don't need a `DataLoader` at all; just use the WebDataset directly. 

However, you do need to explicitly set the `nodesplitter` and `splitter` to nothing since otherwise it's going to attempt to split the noise dataset as well based on the PyTorch node/worker global info (I don't like these magic global variables, but that's the default behavior PyTorch users expect right now).

By the way, for the type declaration, you can probably just say `IterableDataset`; that's the interface everything dataset in WebDataset conforms to, with `Processor` being more of a convenience function.

```
def no_split(urls):
    return urls

noise_data = wds.WebDataset("noise-{000..004}.tar", nodesplitter=no_split, splitter=no_split).decode("pil").repeat().shuffle(10)

class Augmenter:
    def __init__(self, noise_source: IterableDataset):
        self.iter = iter(noise_source)

    def get_noise(self):
        noise_dict = next(self.iter)

        return noise_dict["noise.pyd"]

    def augment(self, sample: dict):
        augmented_x = sample["x.pyd"] + self.get_noise()

        return {**sample, "x.pyd": augmented_x}
```
