### ISSUE TITLE
Using wds.handle_extension prevents Webdaset to be pickle compatible

### ISSUE THREAD

**Issue by hal-314** [tmbdev/webdataset#63]
Hi

First of all, it's a great library! 

I'm working with custom data and I add a custom decoder through `wds.handle_extension`. However, when I try to train with Pytorch Lightning + Horovod, the resulting webdataset can't be pickled.  `wds.handle_extension` uses a local function (`g`) to wrap the custom decode function. Local functions are supported by pickle.

Steps to reproduce:
```python

import pickle
import webdataset as wds
def foo_handler(data):
     return data

dataset = wds.WebDataset(['url_1', 'url_2']) .decode(wds.handle_extension('.foo', foo_handler)) 

pickle.dumps(dataset)
```
Stack error

```
AttributeError                            Traceback (most recent call last)
<ipython-input-25-52f3e267b248> in <module>
----> 1 pickle.dumps(dataset)

AttributeError: Can't pickle local object 'handle_extension.<locals>.g'
```

The solution would be moving `g` out of  `wds.handler`

**Comment by tmbdev** [comment]
Thanks; I have incorporated the patch.
