### ISSUE TITLE
What happens when number of shards are less than the number of workers or not divisable by the workers?

### ISSUE THREAD

**Issue by VahidooX** [tmbdev/webdataset#65]
Hi, thanks for building and sharing this library. It is very nice.

I have a question on the cases where the number of shards are less than workers or they are not divisiable by number of workers. What would happen? It is going to give a warning here: https://github.com/tmbdev/webdataset/blob/master/webdataset/workerenv.py#L118

But what would really happen when workers do not have the same number of shards? Do the dataloader's workers just repeat and start from the first shard when reaches to their last shard?

**Comment by tmbdev** [comment]
Each worker just produces output for all the shards it has and then finishes. By default, WebDataset gives you each training sample exactly once during each epoch, even with multiple workers. It can be desirable to override this default behavior by using .repeat, but you have to explicitly request it.

For large scale training, epochs don't make much sense; in that case, it's best just to use .repeat() on the datasets and possibly also to turn off node splitting. In that case, all workers just yield a continuous stream of samples from the entire dataset. If your code is "epoch based", you can still create "epochs" that are smaller than the original dataset with ResizedDataset or islice.
